I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Alinor.rpy", line 26, in script
    $ call_shop('Лавка кондитера', amy_shop)
  File "game/Alinor.rpy", line 26, in <module>
    $ call_shop('Лавка кондитера', amy_shop)
  File "game/System.rpy", line 47, in call_shop
    renpy.call_screen('game_shop')
  File "game/Shop.rpy", line 36, in execute
    screen game_shop:
  File "game/Shop.rpy", line 36, in execute
    screen game_shop:
  File "game/Shop.rpy", line 156, in execute
    for i in range(7):
  File "game/Shop.rpy", line 157, in execute
    if shop_item_exist<len(shop_items): #ПОТОМ ИЗМЕНИТЬ НА ФУНКЦИЮ, ЧТОБЫ ИМЯ МАГАЗИНА САМО ПОДСТАВЛЯЛОСЬ
  File "game/Shop.rpy", line 159, in execute
    $shop_item_idenfity(i)
  File "game/Shop.rpy", line 159, in <module>
    $shop_item_idenfity(i)
  File "game/System.rpy", line 60, in shop_item_idenfity
    shop_item_name=shop_items[i+shop_i_plus][0].name
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Alinor.rpy", line 26, in script
    $ call_shop('Лавка кондитера', amy_shop)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 848, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\python.py", line 1812, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Alinor.rpy", line 26, in <module>
    $ call_shop('Лавка кондитера', amy_shop)
  File "game/System.rpy", line 47, in call_shop
    renpy.call_screen('game_shop')
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\exports.py", line 2655, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 2624, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 2999, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 511, in visit_all
    d.visit_all(callback)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 511, in visit_all
    d.visit_all(callback)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 511, in visit_all
    d.visit_all(callback)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\screen.py", line 401, in visit_all
    callback(self)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 2999, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\screen.py", line 411, in per_interact
    self.update()
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\screen.py", line 592, in update
    self.screen.function(**self.scope)
  File "game/Shop.rpy", line 36, in execute
    screen game_shop:
  File "game/Shop.rpy", line 36, in execute
    screen game_shop:
  File "game/Shop.rpy", line 156, in execute
    for i in range(7):
  File "game/Shop.rpy", line 157, in execute
    if shop_item_exist<len(shop_items): #ПОТОМ ИЗМЕНИТЬ НА ФУНКЦИЮ, ЧТОБЫ ИМЯ МАГАЗИНА САМО ПОДСТАВЛЯЛОСЬ
  File "game/Shop.rpy", line 159, in execute
    $shop_item_idenfity(i)
  File "game/Shop.rpy", line 159, in <module>
    $shop_item_idenfity(i)
  File "game/System.rpy", line 60, in shop_item_idenfity
    shop_item_name=shop_items[i+shop_i_plus][0].name
IndexError: list index out of range

Windows-7-6.1.7601-SP1
Ren'Py 6.99.14.1.3218
 
Mon Dec 17 00:00:11 2018
